[window]
opacity = 0.75

blur = true
dimensions = { columns = 100, lines = 25 }


[colors.primary]
background = "#000131"


[font]
bold = { family = "CodeNewRoman Nerd Font", style = "Bold" }
normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }
italic = { family = "CodeNewRoman Nerd Font", style = "Italic" }
bold_italic = { family = "CodeNewRoman Nerd Font", style = "Bold Italic" }

builtin_box_drawing = true

size = 8
