[window]
opacity = 0.55

blur = true
dimensions = { columns = 100, lines = 25 }


[colors.primary]
background = "#000131"


[font]
# bold = { family = "Bitstrom Wera Mono", style = "Bold" }
# normal = { family = "Bitstrom Wera Mono", style = "Regular" }

builtin_box_drawing = true

size = 8
