import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]


[window]
opacity = 0.75

blur = true
dimensions = { columns = 100, lines = 25 }


[colors.primary]
background = "#000131"


[font]
bold = { family = "CodeNewRoman Nerd Font Mono", style = "Bold" }
normal = { family = "CodeNewRoman Nerd Font Mono", style = "Regular" }
italic = { family = "CodeNewRoman Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CodeNewRoman Nerd Font Mono", style = "Bold Italic" }

builtin_box_drawing = true

size = 8
