[window]
opacity = 0.75
blur = true
decorations = "Transparent"


[colors.primary]
background = "#000011"


[font]
# bold = { family = "Bitstrom Wera Mono", style = "Bold" }
# normal = { family = "Bitstrom Wera Mono", style = "Regular" }

builtin_box_drawing = true

size = 8.5
